version: '3.8'

services:
  debian32:
    image: "hlds3111e:latest"
    container_name: hlds3111ecs15
    restart: unless-stopped
    user: "0:0"  # Run as root (consider using a non-root user for security)
    tty: true
    stdin_open: true
#    volumes:
#      - /opt/cstrike/addons:/server/hlds_l/cstrike/addons #replace with your game mode path
    ports:
      - 27016:27016/tcp
      - 27016:27016/udp
    command: >
      ./hlds_run +ip 0.0.0.0 +port 27016 -game cstrike +map de_dust +maxplayers 16 -noauth -insecure +sv_lan 1
    security_opt:
      - no-new-privileges:1
